[package]
name = "vec_derive"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]
vec_macros = {path = "../vec_macros"}
syn = "0.10.6"
quote = "0.3.10"
rustfmt = "*"
itertools = "*"

[lib]
proc-macro = true
